MODEL:
  META_ARCHITECTURE: "IENet"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  AVOD:
    HEAD_NAME: "AVODWH_CENTER"
    NUM_CONVS: 4
    # normalizing the regression targets with FPN strides
    NORM_REG_TARGETS: True
    # positioning centerness on the regress branch.
    # Please refer to https://github.com/tianzhi0549/FCOS/issues/89#issuecomment-516877042
    CENTERNESS_ON_REG: True
    # using center sampling and GIoU.
    # Please refer to https://github.com/yqyao/FCOS_PLUS
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
    # we only use dcn in the last layer of towers
    USE_DCN_IN_TOWER: False
    INDEPENDENT_BRANCH: False
    ATTENTION_ON: False
    PRE_NMS_TOP_N: 3000
    IN_FEATURES: ["p3", "p4", "p5", "p6", "p7"]
DATASETS:
  TRAIN: ("dota_train_800", "dota_val_800",)
  TEST: ("dota_val_mini_800",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (110000, 130000, 150000)
  MAX_ITER: 150000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 800
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 16
  ASPECT_RATIO_GROUPING: False
TEST:
  AUG:
    MIN_SIZES: (800,)
    MAX_SIZE: 800
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 2000
