_BASE_: "Base-IENet-retina_p6p7.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  AVOD:
    INDEPENDENT_BRANCH: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  MAX_ITER: 140000
  STEPS: (80000, 100000, 120000)
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ("dota_train_800", "dota_val_800",)
  TEST: ("dota_val_mini_800",)
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/home/omnisky/Pengming_workspace/disk_2T/DOTA/training/ienet/avod_center_demo_v2"
