_BASE_: "Base-IENet-retina_p6p7.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  AVOD:
    INDEPENDENT_BRANCH: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: (210000, 250000)
  MAX_ITER: 270000
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ("dota_train_800", "dota_val_800",)
  TEST: ("dota_test_800_aug",)
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/home/omnisky/Pengming_workspace/disk_2T/DOTA/training/ienet/avod_center_demo_v3"
