_BASE_: "Base-IENet-retina_p6p7.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  AVOD:
    INFERENCE_TH: 0.05
    INDEPENDENT_BRANCH: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0005
  STEPS: (140000, 190000)
  MAX_ITER: 200000
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ("dota_train_800_aug", "dota_val_800_aug",)
  TEST: ("dota_val_mini_800",)
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "/home/omnisky/Pengming_workspace/disk_2T/DOTA/training/ienet/avod_center_demo_v3"
