_BASE_: "Base-IENet-retina_p6p7.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  AVOD:
    INFERENCE_TH: 0.05
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  MAX_ITER: 140000
  STEPS: (80000, 100000, 120000)
DATALOADER:
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 0
DATASETS:
  TEST: ("dota_test_800",)
OUTPUT_DIR: "/home/omnisky/Pengming_workspace/disk_2T/DOTA/training/ienet/avod_center_demo"
